version: '3.9'
services:
  db:
    image: mysql:8.0
    container_name: mysql_container
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=user
      - MYSQL_USER=user
      - MYSQL_DATABASE=test_db
  app:
    depends_on:
      - db
    container_name: my_app
    build:
      dockerfile: dockerfile
      args:
        DOCKER_BUILDKIT: 1